"""Example 15: Schema Validation & Diagnostic Suggestions for Graph Agents.

Demonstrates Voyager's native schema validation layer:
1. Register domain models (`Person`, `Movie`) into the global `SchemaRegistry`.
2. Validate raw Cypher queries before executing them against a database.
3. Catch typos and invalid graph structures with Levenshtein fuzzy suggestions (`UNKNOWN_NODE_LABEL`).
4. Enforce strict query safety using `report.raise_if_invalid()`.

Run with: `uv run python examples/python/15_schema_validation.py`
"""

from __future__ import annotations

from voyager_ogm import (
    Field,
    Node,
    Relationship,
    SchemaRegistry,
    SchemaValidationError,
    node,
    relationship,
    validate_query,
)


@node(labels=["Person"])
class Person(Node):
    name: str = Field(primary_key=True)
    age: int = Field(default=30)


@node(labels=["Movie"])
class Movie(Node):
    title: str = Field(primary_key=True)
    released: int = Field(default=2000)


@relationship(type_name="ACTED_IN")
class ActedIn(Relationship):
    role: str = Field(default="Actor")


def main() -> None:
    print("=" * 70)
    print("[Example 15] Schema Validation & Diagnostic Suggestions")
    print("=" * 70)

    # 1. Register schemas in the global registry
    reg = SchemaRegistry.global_registry()
    Person.register_schema(reg)
    Movie.register_schema(reg)
    reg.register_relationship(
        name="ActedIn",
        type_name="ACTED_IN",
        source_labels=["Person"],
        target_labels=["Movie"],
        fields={"role": {"type": "STRING"}},
        directed=True,
    )
    print("1. Registered Schema Entities: Person, Movie, ACTED_IN\n")

    # 2. Inspect a query generated by an LLM or user with a typo ('Persn')
    bad_query = "MATCH (p:Persn)-[r:ACTED_IN]->(m:Movie) RETURN p.name, m.title"
    print(f"2. Validating LLM/Agent Query:\n   {bad_query}\n")

    report = validate_query(bad_query)
    print(f"   Validation Passed : {report.is_valid}")
    print(f"   Diagnostic Count  : {len(report.diagnostics)}")

    # 3. Inspect diagnostics with intelligent error codes and suggestions
    for diag in report.diagnostics:
        print("\n   [Diagnostic Detected]")
        print(f"     Severity   : {diag.severity.upper()}")
        print(f"     Code       : {diag.code}")
        print(f"     Entity     : {diag.entity_id}")
        print(f"     Message    : {diag.message}")
        if diag.suggestion:
            print(f"     Suggestion : {diag.suggestion}")

    # 4. Demonstrate raising SchemaValidationError
    print("\n3. Enforcing query safety with report.raise_if_invalid():")
    try:
        report.raise_if_invalid()
    except SchemaValidationError as exc:
        print(f"   [CAUGHT EXPECTED ERROR]: {exc}\n")

    # 5. Validate a conforming query
    good_query = "MATCH (p:Person)-[r:ACTED_IN]->(m:Movie) RETURN p.name, m.title"
    print(f"4. Validating Corrected Query:\n   {good_query}")
    valid_report = validate_query(good_query)
    valid_report.raise_if_invalid()
    print(f"   Validation Passed : {valid_report.is_valid} (0 errors)")
    print("=" * 70)


if __name__ == "__main__":
    main()
