[package]
name = "voyager-pyo3"
description = "Python PyO3 bindings and Apache Arrow PyCapsule bridge for Voyager OGM"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
name = "_voyager_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
voyager-core = { workspace = true, features = ["serde", "arrow"] }
arrow = { workspace = true }
pyo3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
