"""Voyager OGM: Multi-Dialect, Vendor-Neutral Object-Graph Mapper."""

from voyager_ogm import expressions, fn, types
from voyager_ogm._voyager_rs import (
    ArrowStream,
    AstExpr,
    NativeCircuitRouter,
    NativeClient,
    NativeQueryBuilder,
    NativeQueryResult,
    NativeSchemaRegistry,
    compile_query_from_spec,
    extract_topology_from_query,
    generate_synthetic_stream,
    version,
)
from voyager_ogm.bridge import (
    AsyncDatabaseBridge,
    AsyncDuckDbBridge,
    AsyncFalkorDBBridge,
    AsyncMockBridge,
    AsyncNeo4jBoltBridge,
    AsyncPostgresBridge,
    BulkExecutionResult,
    DatabaseBridge,
    DuckDbBridge,
    FalkorDBBridge,
    MockBridge,
    Neo4jBoltBridge,
    PostgresBridge,
    create_bridge,
    register_bridge,
)
from voyager_ogm.config import VoyagerConfig, configure, get_config, reset_config
from voyager_ogm.expressions import (
    AliasedExpr,
    BinaryExpr,
    CaseBuilder,
    CaseExpr,
    Expression,
    FunctionExpr,
    IdentExpr,
    ListCompExpr,
    ListLiteralExpr,
    LiteralExpr,
    ParamExpr,
    PatternCompExpr,
    PropExpr,
    SubqueryExpr,
    case,
    col,
    ident,
    list_comprehension,
    lit,
    param,
    pattern_comprehension,
    prop,
    to_expression,
)
from voyager_ogm.hybrid import AsyncHybridSession, HybridQuery, HybridSession
from voyager_ogm.ingestion import (
    BulkIngestionBatch,
    BulkIngestionPlan,
    chunk_dataframe,
    chunk_records,
    create_bulk_create_plan,
    create_bulk_create_rel_plan,
    create_bulk_merge_plan,
)
from voyager_ogm.models import (
    BoundField,
    Field,
    Node,
    PredicateExpr,
    Relationship,
    node,
    relationship,
    reset_alias_counters,
)
from voyager_ogm.query import (
    ColumnMeta,
    CompiledQuery,
    ConformanceDiagnostic,
    ConformanceReport,
    Path,
    Query,
    SchemaValidationError,
    explain,
    profile,
    validate_query,
)
from voyager_ogm.schema import SchemaManager, SchemaRegistry
from voyager_ogm.session import (
    AsyncSession,
    ExecutionResult,
    MappingsResult,
    Result,
    ScalarsResult,
    Session,
)
from voyager_ogm.sqlalchemy import (
    GraphRelationshipProperty,
    GraphTableClause,
    PropertyGraph,
    as_cte,
    graph_relationship,
    graph_table,
)
from voyager_ogm.streaming import QueryResult, to_arrow, to_polars
from voyager_ogm.transaction import SavepointContext, Transaction
from voyager_ogm.types import Point
from voyager_ogm.viewer import GraphViewer, explore, show, view_graph, visualize_query

__version__ = version()

# Ergonomic Aliases
func = fn
func_ = fn
query = Query
GraphQuery = Query

__all__ = [
    "AliasedExpr",
    "ArrowStream",
    "AstExpr",
    "AsyncDatabaseBridge",
    "AsyncDuckDbBridge",
    "AsyncFalkorDBBridge",
    "AsyncHybridSession",
    "AsyncMockBridge",
    "AsyncNeo4jBoltBridge",
    "AsyncPostgresBridge",
    "AsyncSession",
    "BinaryExpr",
    "BoundField",
    "BulkExecutionResult",
    "BulkIngestionBatch",
    "BulkIngestionPlan",
    "CaseBuilder",
    "CaseExpr",
    "ColumnMeta",
    "CompiledQuery",
    "compile_query_from_spec",
    "ConformanceDiagnostic",
    "ConformanceReport",
    "DatabaseBridge",
    "DuckDbBridge",
    "ExecutionResult",
    "Expression",
    "FalkorDBBridge",
    "Field",
    "FunctionExpr",
    "GraphQuery",
    "GraphRelationshipProperty",
    "GraphTableClause",
    "GraphViewer",
    "HybridQuery",
    "HybridSession",
    "IdentExpr",
    "ListCompExpr",
    "ListLiteralExpr",
    "LiteralExpr",
    "MappingsResult",
    "MockBridge",
    "NativeCircuitRouter",
    "NativeClient",
    "NativeQueryBuilder",
    "NativeQueryResult",
    "NativeSchemaRegistry",
    "Neo4jBoltBridge",
    "Node",
    "ParamExpr",
    "Path",
    "Point",
    "PatternCompExpr",
    "PostgresBridge",
    "PredicateExpr",
    "PropExpr",
    "PropertyGraph",
    "Query",
    "QueryResult",
    "Relationship",
    "Result",
    "SavepointContext",
    "ScalarsResult",
    "SchemaManager",
    "SchemaRegistry",
    "SchemaValidationError",
    "Session",
    "SubqueryExpr",
    "Transaction",
    "VoyagerConfig",
    "as_cte",
    "case",
    "chunk_dataframe",
    "chunk_records",
    "col",
    "configure",
    "create_bridge",
    "create_bulk_create_plan",
    "create_bulk_create_rel_plan",
    "create_bulk_merge_plan",
    "explain",
    "explore",
    "expressions",
    "extract_topology_from_query",
    "fn",
    "func",
    "func_",
    "generate_synthetic_stream",
    "get_config",
    "graph_relationship",
    "graph_table",
    "ident",
    "list_comprehension",
    "lit",
    "node",
    "param",
    "pattern_comprehension",
    "profile",
    "prop",
    "query",
    "register_bridge",
    "relationship",
    "reset_alias_counters",
    "reset_config",
    "show",
    "to_arrow",
    "to_expression",
    "to_polars",
    "types",
    "validate_query",
    "version",
    "view_graph",
    "visualize_query",
]
