"""Type stubs for the native Rust PyO3 extension module `_voyager_rs`."""

from __future__ import annotations

from typing import Any

class NativeQueryBuilder:
    """Native Rust Query Builder arena wrapper."""

    def __init__(self) -> None: ...
    def match(self) -> None: ...
    def optional_match(self) -> None: ...
    def node(self, variable: str | None = None, labels: list[str] | None = None) -> None: ...
    def to(self, edge_types: list[str] | None = None, variable: str | None = None) -> None: ...
    def from_edge(
        self, edge_types: list[str] | None = None, variable: str | None = None
    ) -> None: ...
    def edge(self, edge_types: list[str] | None = None, variable: str | None = None) -> None: ...
    def hops(self, min: int, max: int) -> None: ...
    def where_eq(self, var: str, prop: str, val: Any) -> None: ...
    def where_gt(self, var: str, prop: str, val: Any) -> None: ...
    def where_gte(self, var: str, prop: str, val: Any) -> None: ...
    def where_lt(self, var: str, prop: str, val: Any) -> None: ...
    def where_lte(self, var: str, prop: str, val: Any) -> None: ...
    def where_contains(self, var: str, prop: str, val: str) -> None: ...
    def return_(self) -> None: ...
    def create(self) -> None: ...
    def merge(self) -> None: ...
    def on_create_set(self, var: str, prop: str, val: Any) -> None: ...
    def on_match_set(self, var: str, prop: str, val: Any) -> None: ...
    def set_property(self, var: str, prop: str, val: Any) -> None: ...
    def delete(self, targets: list[str]) -> None: ...
    def detach_delete(self, targets: list[str]) -> None: ...
    def unwind(self, param_name: str, alias: str) -> None: ...
    def load_csv(self, url: str, with_headers: bool = True, alias: str = "row") -> None: ...
    def remove_property(self, var: str, prop: str) -> None: ...
    def field(self, var: str, prop: str, alias: str | None = None) -> None: ...
    def aggregate(self, var: str, prop: str, func: str, alias: str | None = None) -> None: ...
    def order_by(self, var: str, prop: str, ascending: bool) -> None: ...
    def distinct(self) -> None: ...
    def limit(self, limit: int) -> None: ...
    def skip(self, skip: int) -> None: ...
    def call_procedure(
        self, procedure_name: str, args: list[Any], kwargs: dict[str, Any]
    ) -> None: ...
    def yield_items(self, items: list[str]) -> None: ...
    def compile(self, dialect: str = "cypher", graph_name: str | None = None) -> dict[str, Any]: ...

class NativeTransaction:
    """Native Unit-of-Work transaction with dirty arena state rollback."""

    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def state(self) -> str: ...
    @property
    def is_active(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def savepoint(self, name: str) -> None: ...
    def rollback_to_savepoint(self, name: str) -> None: ...
    def release_savepoint(self, name: str) -> None: ...

class NativeUnitOfWork:
    """Native In-Memory Unit of Work for dirty entity state management."""

    def __init__(self) -> None: ...
    @property
    def len(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...

class ArrowStream:
    """Native Apache Arrow C-Data Stream export interface."""

    def __init__(self, count: int = 1000) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: Any = None) -> Any: ...

def generate_synthetic_stream(count: int) -> ArrowStream: ...
def version() -> str: ...
def compile_bulk_create(
    label: str,
    properties: list[str],
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
def compile_bulk_merge(
    label: str,
    key_property: str,
    properties: list[str],
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
def compile_bulk_create_rel(
    rel_type: str,
    properties: list[str],
    from_label: str,
    from_key: str,
    to_label: str,
    to_key: str,
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
