"""Type stubs for the native Rust PyO3 extension module `_voyager_rs`."""

from __future__ import annotations

from typing import Any

class NativeQueryBuilder:
    """Native Rust Query Builder arena wrapper."""

    def __init__(self) -> None: ...
    def match(self) -> None: ...
    def optional_match(self) -> None: ...
    def node(self, variable: str | None = None, labels: list[str] | None = None) -> None: ...
    def to(self, edge_types: list[str] | None = None, variable: str | None = None) -> None: ...
    def from_edge(
        self, edge_types: list[str] | None = None, variable: str | None = None
    ) -> None: ...
    def edge(self, edge_types: list[str] | None = None, variable: str | None = None) -> None: ...
    def hops(self, min: int, max: int) -> None: ...
    def trail(self, variable: str | None = None) -> None: ...
    def simple(self, variable: str | None = None) -> None: ...
    def acyclic(self, variable: str | None = None) -> None: ...
    def walk(self, variable: str | None = None) -> None: ...
    def path_variable(self, variable: str) -> None: ...
    def path_mode(self, mode: str) -> None: ...
    def get_path_mode(self) -> str | None: ...
    def where_property(self, var: str, prop: str, op: str, val: Any) -> None: ...
    def where_eq(self, var: str, prop: str, val: Any) -> None: ...
    def where_ne(self, var: str, prop: str, val: Any) -> None: ...
    def where_gt(self, var: str, prop: str, val: Any) -> None: ...
    def where_gte(self, var: str, prop: str, val: Any) -> None: ...
    def where_lt(self, var: str, prop: str, val: Any) -> None: ...
    def where_lte(self, var: str, prop: str, val: Any) -> None: ...
    def where_in(self, var: str, prop: str, val: Any) -> None: ...
    def where_not_in(self, var: str, prop: str, val: Any) -> None: ...
    def where_contains(self, var: str, prop: str, val: str) -> None: ...
    def where_starts_with(self, var: str, prop: str, val: str) -> None: ...
    def where_ends_with(self, var: str, prop: str, val: str) -> None: ...
    def return_(self) -> None: ...
    def with_(self) -> None: ...
    def create(self) -> None: ...
    def merge(self) -> None: ...
    def on_create_set(self, var: str, prop: str, val: Any) -> None: ...
    def on_match_set(self, var: str, prop: str, val: Any) -> None: ...
    def set_property(self, var: str, prop: str, val: Any) -> None: ...
    def delete(self, targets: list[str]) -> None: ...
    def detach_delete(self, targets: list[str]) -> None: ...
    def unwind(self, param_name: str, alias: str) -> None: ...
    def load_csv(self, url: str, with_headers: bool = True, alias: str = "row") -> None: ...
    def remove_property(self, var: str, prop: str) -> None: ...
    def field(self, var: str, prop: str, alias: str | None = None) -> None: ...
    def aggregate(self, var: str, prop: str, func: str, alias: str | None = None) -> None: ...
    def order_by(self, var: str, prop: str, ascending: bool) -> None: ...
    def pattern(self) -> None: ...
    def where_expr(self, expr_spec: Any) -> None: ...
    def select_expr(self, expr_spec: Any, alias: str | None = None) -> None: ...
    def order_by_expr(self, expr_spec: Any, ascending: bool = True) -> None: ...
    def distinct(self) -> None: ...
    def limit(self, limit: int) -> None: ...
    def skip(self, skip: int) -> None: ...
    def offset(self, offset: int) -> None: ...
    def let_(self, variable: str, expr: Any) -> None: ...
    def filter_(self, predicate: Any) -> None: ...
    def linear_filter(self, predicate: Any) -> None: ...
    def call_procedure(
        self, procedure_name: str, args: list[Any], kwargs: dict[str, Any]
    ) -> None: ...
    def yield_items(self, items: list[str]) -> None: ...
    def explain(self) -> None: ...
    def profile(self) -> None: ...
    def execution_mode(self) -> str: ...
    def clone_builder(self) -> NativeQueryBuilder: ...
    def __copy__(self) -> NativeQueryBuilder: ...
    def __deepcopy__(self, memo: Any) -> NativeQueryBuilder: ...
    def compile(
        self,
        dialect: str = "cypher",
        graph_name: str | None = None,
        optimize: bool = False,
        optimization_level: str = "standard",
    ) -> dict[str, Any]: ...

class NativeTransaction:
    """Native Unit-of-Work transaction with dirty arena state rollback."""

    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def state(self) -> str: ...
    @property
    def is_active(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def savepoint(self, name: str) -> None: ...
    def rollback_to_savepoint(self, name: str) -> None: ...
    def release_savepoint(self, name: str) -> None: ...

class NativeUnitOfWork:
    """Native In-Memory Unit of Work for dirty entity state management."""

    def __init__(self) -> None: ...
    @property
    def len(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...

class NativeSchemaRegistry:
    """Centralized, thread-safe Native Schema Registry for graph models and property metadata."""

    def __init__(self) -> None: ...
    @staticmethod
    def global_registry() -> NativeSchemaRegistry: ...
    @staticmethod
    def global_() -> NativeSchemaRegistry: ...
    def register_node(
        self,
        name: str,
        labels: list[str],
        fields: dict[str, Any] | list[dict[str, Any]],
        primary_key: str | None = None,
    ) -> None: ...
    def register_node_schema(self, schema: dict[str, Any]) -> None: ...
    def register_relationship(
        self,
        name: str,
        type_name: str,
        source_labels: list[str] | None = None,
        target_labels: list[str] | None = None,
        fields: dict[str, Any] | list[dict[str, Any]] | None = None,
        directed: bool = True,
    ) -> None: ...
    def register_relationship_schema(self, schema: dict[str, Any]) -> None: ...
    def get_node(self, name: str) -> dict[str, Any] | None: ...
    def get_node_by_label(self, label: str) -> dict[str, Any] | None: ...
    def get_relationship(self, name: str) -> dict[str, Any] | None: ...
    def get_relationship_by_type(self, type_name: str) -> dict[str, Any] | None: ...
    def has_node(self, name: str) -> bool: ...
    def has_relationship(self, name: str) -> bool: ...
    def remove_node(self, name: str) -> dict[str, Any] | None: ...
    def remove_relationship(self, name: str) -> dict[str, Any] | None: ...
    def node_schemas(self) -> list[dict[str, Any]]: ...
    def relationship_schemas(self) -> list[dict[str, Any]]: ...
    def clear(self) -> None: ...
    def to_json(self) -> str: ...
    def from_json(self, json_str: str) -> None: ...
    def load_json(self, json_str: str) -> None: ...
    def generate_cypher_ddl(
        self, include_type_constraints: bool = False, model_name: str | None = None
    ) -> list[str]: ...
    def generate_cypher_drop_ddl(
        self, include_type_constraints: bool = False, model_name: str | None = None
    ) -> list[str]: ...
    def generate_gql_graph_type_ddl(
        self, graph_type_name: str, model_names: list[str] | None = None
    ) -> str: ...
    def generate_gql_alter_node_ddl(self, node_name: str) -> str | None: ...
    def generate_gql_alter_rel_ddl(
        self,
        rel_name: str,
        source_label: str | None = None,
        target_label: str | None = None,
    ) -> str | None: ...
    def generate_gql_drop_graph_type_ddl(self, graph_type_name: str) -> str: ...
    def generate_pgq_ddl(self, graph_name: str, model_names: list[str] | None = None) -> str: ...
    def generate_pgq_drop_ddl(self, graph_name: str) -> str: ...
    def generate_cypher25_graph_type_ddl(self, model_names: list[str] | None = None) -> str: ...
    def generate_cypher25_drop_graph_type_ddl(self) -> str: ...
    def __len__(self) -> int: ...

class ArrowStream:
    """Native Apache Arrow C-Data Stream export interface."""

    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def is_consumed(self) -> bool: ...
    def __arrow_c_stream__(self, requested_schema: Any = None) -> Any: ...
    def to_dicts(self) -> list[dict[str, Any]]: ...
    def iter_batches(self, batch_size: int = 10000) -> list[ArrowStream]: ...

class NativeQueryResult:
    """Native query result containing columnar Apache Arrow record batch and execution summary counters."""

    @property
    def columns(self) -> list[str]: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def is_consumed(self) -> bool: ...
    @property
    def nodes_created(self) -> int: ...
    @property
    def nodes_deleted(self) -> int: ...
    @property
    def relationships_created(self) -> int: ...
    @property
    def relationships_deleted(self) -> int: ...
    @property
    def properties_set(self) -> int: ...
    @property
    def execution_time_ms(self) -> int: ...
    @property
    def stream(self) -> ArrowStream: ...
    @property
    def records(self) -> list[dict[str, Any]]: ...
    @property
    def summary(self) -> NativeQueryResult: ...
    def __arrow_c_stream__(self, requested_schema: Any = None) -> Any: ...
    def to_dicts(self) -> list[dict[str, Any]]: ...

class NativeClient:
    """Native asynchronous Rust network client managing connection pooling and wire protocols."""

    def __init__(self, uri: str, min_idle: int = 1, max_size: int = 10) -> None: ...
    @property
    def uri(self) -> str: ...
    @property
    def protocol(self) -> str: ...
    def execute_sync(
        self, query: str, params: dict[str, Any] | None = None
    ) -> NativeQueryResult: ...
    async def execute(
        self, query: str, params: dict[str, Any] | None = None
    ) -> NativeQueryResult: ...
    def ping_sync(self) -> bool: ...
    async def ping(self) -> bool: ...
    def close(self) -> None: ...

def generate_synthetic_stream(count: int) -> ArrowStream: ...
def version() -> str: ...
def compile_bulk_create(
    label: str,
    properties: list[str],
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
def compile_bulk_merge(
    label: str,
    key_property: str,
    properties: list[str],
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
def compile_bulk_create_rel(
    rel_type: str,
    properties: list[str],
    from_label: str,
    from_key: str,
    to_label: str,
    to_key: str,
    batch_param: str = "batch",
    row_alias: str = "row",
    dialect: str = "cypher",
) -> dict[str, Any]: ...
def compile_query_from_spec(
    spec: dict[str, Any],
    dialect: str = "cypher",
    graph_name: str | None = None,
    optimize: bool = False,
    optimization_level: str = "standard",
    use_cache: bool = True,
) -> dict[str, Any]: ...
def get_query_cache_stats() -> dict[str, Any]: ...
def clear_query_cache() -> None: ...
def get_runtime_pid() -> int: ...
def emit_cypher_node_ddl(node: Any, include_type_constraints: bool = False) -> list[str]: ...
def emit_cypher_rel_ddl(rel: Any, include_type_constraints: bool = False) -> list[str]: ...
def emit_cypher_drop_node_ddl(node: Any, include_type_constraints: bool = False) -> list[str]: ...
def emit_cypher_drop_rel_ddl(rel: Any, include_type_constraints: bool = False) -> list[str]: ...
def emit_gql_alter_node_ddl(node: Any) -> str: ...
def emit_gql_alter_rel_ddl(
    rel: Any, source_label: str | None = None, target_label: str | None = None
) -> str: ...
def emit_gql_graph_type_ddl(
    graph_type_name: str,
    nodes: list[Any] | None = None,
    rels: list[Any] | None = None,
) -> str: ...
def emit_gql_drop_graph_type_ddl(graph_type_name: str) -> str: ...
def emit_pgq_property_graph_ddl(
    graph_name: str,
    nodes: list[Any] | None = None,
    rels: list[Any] | None = None,
) -> str: ...
def emit_pgq_drop_property_graph_ddl(graph_name: str) -> str: ...
def emit_cypher25_graph_type_ddl(
    nodes: list[Any] | None = None,
    rels: list[Any] | None = None,
) -> str: ...
def emit_cypher25_drop_graph_type_ddl() -> str: ...

class AstExpr:
    """Native AST Expression node handle wrapping a lightweight AST arena."""

    @staticmethod
    def prop(var: str, prop: str) -> AstExpr: ...
    @staticmethod
    def ident(name: str) -> AstExpr: ...
    @staticmethod
    def literal(val: Any) -> AstExpr: ...
    @staticmethod
    def binary(left: Any, op: str, right: Any) -> AstExpr: ...
    @staticmethod
    def unary(op: str, operand: Any) -> AstExpr: ...
    @staticmethod
    def function(name: str, args: list[Any]) -> AstExpr: ...
    def in_(self, other: Any) -> AstExpr: ...
    def not_in(self, other: Any) -> AstExpr: ...
    def contains(self, other: Any) -> AstExpr: ...
    def startswith(self, other: Any) -> AstExpr: ...
    def endswith(self, other: Any) -> AstExpr: ...
    def is_null(self) -> AstExpr: ...
    def is_not_null(self) -> AstExpr: ...
    def __add__(self, other: Any) -> AstExpr: ...
    def __radd__(self, other: Any) -> AstExpr: ...
    def __sub__(self, other: Any) -> AstExpr: ...
    def __rsub__(self, other: Any) -> AstExpr: ...
    def __mul__(self, other: Any) -> AstExpr: ...
    def __rmul__(self, other: Any) -> AstExpr: ...
    def __truediv__(self, other: Any) -> AstExpr: ...
    def __rtruediv__(self, other: Any) -> AstExpr: ...
    def __mod__(self, other: Any) -> AstExpr: ...
    def __rmod__(self, other: Any) -> AstExpr: ...
    def __neg__(self) -> AstExpr: ...
    def __and__(self, other: Any) -> AstExpr: ...
    def __rand__(self, other: Any) -> AstExpr: ...
    def __or__(self, other: Any) -> AstExpr: ...
    def __ror__(self, other: Any) -> AstExpr: ...
    def __xor__(self, other: Any) -> AstExpr: ...
    def __rxor__(self, other: Any) -> AstExpr: ...
    def __invert__(self) -> AstExpr: ...
    def __eq__(self, other: Any) -> AstExpr: ...  # ty: ignore[invalid-method-override] # type: ignore[override]
    def __ne__(self, other: Any) -> AstExpr: ...  # ty: ignore[invalid-method-override] # type: ignore[override]
    def __lt__(self, other: Any) -> AstExpr: ...
    def __le__(self, other: Any) -> AstExpr: ...
    def __gt__(self, other: Any) -> AstExpr: ...
    def __ge__(self, other: Any) -> AstExpr: ...
