"""Session management and high-level execution facade for Voyager OGM."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from voyager_ogm.bridge import (
    AsyncDatabaseBridge,
    BulkExecutionResult,
    DatabaseBridge,
    create_bridge,
)
from voyager_ogm.ingestion import (
    BulkIngestionPlan,
    create_bulk_create_plan,
    create_bulk_create_rel_plan,
    create_bulk_merge_plan,
)
from voyager_ogm.transaction import Transaction

if TYPE_CHECKING:
    import polars as pl

    from voyager_ogm.models import Node, Relationship
    from voyager_ogm.query import Query


class Session:
    """Synchronous graph database session coordinator for Voyager OGM.

    Provides high-throughput bulk ingestion, Unit-of-Work transactions, and query dispatch
    over pluggable database drivers (Neo4j, Memgraph, DuckDB, Mock, etc.).
    """

    def __init__(self, bridge: Any = None, dialect: str = "cypher") -> None:
        """Initializes a new Voyager Session.

        Args:
            bridge: Pluggable database driver (Neo4j Driver, DuckDB connection, MockBridge, etc.).
                If omitted or None, defaults to MockBridge.
            dialect: Default query dialect for statements generated by this session
                ('cypher', 'iso_gql', 'sql_pgq').
        """
        self._dialect = dialect
        self._bridge: DatabaseBridge = create_bridge(bridge, is_async=False)  # type: ignore[assignment]

    @property
    def dialect(self) -> str:
        """Active dialect for this session."""
        return self._dialect

    @property
    def bridge(self) -> DatabaseBridge:
        """Active database bridge."""
        return self._bridge

    def execute(
        self, query_or_statement: Query | str, parameters: dict[str, Any] | None = None
    ) -> list[dict[str, Any]]:
        """Executes a Query object or raw Cypher/GQL statement through the bridge.

        Args:
            query_or_statement: Voyager Query instance or raw query statement string.
            parameters: Query parameters dictionary (if statement is a string).

        Returns:
            List of result records mapped as dictionaries.
        """
        if hasattr(query_or_statement, "compile"):
            compiled = query_or_statement.compile(dialect=self._dialect)
            return self._bridge.execute(compiled.statement, compiled.parameters)
        return self._bridge.execute(str(query_or_statement), parameters)

    def execute_to_polars(
        self, query_or_statement: Query | str, parameters: dict[str, Any] | None = None
    ) -> pl.DataFrame:
        """Executes a query and streams results directly into a Polars DataFrame.

        Args:
            query_or_statement: Voyager Query instance or raw query statement string.
            parameters: Query parameters dictionary (if statement is a string).

        Returns:
            Columnar Polars DataFrame containing the result records.
        """
        if hasattr(query_or_statement, "compile"):
            compiled = query_or_statement.compile(dialect=self._dialect)
            return self._bridge.execute_to_polars(compiled.statement, compiled.parameters)
        return self._bridge.execute_to_polars(str(query_or_statement), parameters)

    def run_bulk(self, plan: BulkIngestionPlan) -> BulkExecutionResult:
        """Dispatches and executes a BulkIngestionPlan across the database bridge.

        Args:
            plan: Prepared bulk ingestion plan generated by bulk_create/bulk_upsert.

        Returns:
            Execution metrics summary including total batches, records, and elapsed time.
        """
        return self._bridge.execute_bulk(plan)

    def transaction(self) -> Transaction:
        """Creates a fresh two-layer rollback transaction context manager.

        Returns:
            Active transaction instance with savepoint support.
        """
        return Transaction()

    def bulk_create(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput bulk node creation execution plan.

        Compiles `UNWIND $batch AS row CREATE (n:Model) SET n.prop = row.prop` and chunks
        the input data/DataFrame into optimal batches.

        Args:
            model: Node class to instantiate.
            data: Records or Polars DataFrame to insert.
            batch_size: Maximum records per batch transaction.
            dialect: Override the session default dialect.

        Returns:
            Executable plan containing parameterized batch queries.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_plan(
            model=model,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_upsert(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        key_field: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput idempotent bulk upsert (MERGE) execution plan.

        Compiles `UNWIND $batch AS row MERGE (n:Model {key: row.key})` with
        `ON CREATE SET ... ON MATCH SET ...` and chunks the input data/DataFrame.

        Args:
            model: Node class to upsert.
            data: Records or Polars DataFrame to upsert.
            key_field: Unique key property field name.
            batch_size: Maximum records per batch transaction.
            dialect: Override the session default dialect.

        Returns:
            Executable plan containing parameterized batch queries.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_merge_plan(
            model=model,
            key_field=key_field,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_create_relationships(
        self,
        rel_model: type[Relationship] | str,
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        from_label: str,
        from_key: str,
        to_label: str,
        to_key: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput bulk relationship creation execution plan.

        Args:
            rel_model: Relationship class or type string.
            data: Records containing `from_<from_key>`, `to_<to_key>`, and edge properties.
            from_label: Source node label.
            from_key: Source node matching property name.
            to_label: Target node label.
            to_key: Target node matching property name.
            batch_size: Maximum edges per batch transaction.
            dialect: Override the session default dialect.

        Returns:
            Executable plan.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_rel_plan(
            rel_model=rel_model,
            data=data,
            from_label=from_label,
            from_key=from_key,
            to_label=to_label,
            to_key=to_key,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def close(self) -> None:
        """Closes the underlying database bridge connection."""
        self._bridge.close()


class AsyncSession:
    """Asynchronous graph database session coordinator for Voyager OGM.

    Provides non-blocking async/await query execution and bulk ingestion over
    async database drivers (e.g. neo4j.AsyncDriver).
    """

    def __init__(self, bridge: Any = None, dialect: str = "cypher") -> None:
        """Initializes a new asynchronous Voyager Session.

        Args:
            bridge: Pluggable async database driver (neo4j.AsyncDriver, AsyncMockBridge, etc.).
            dialect: Default query dialect for statements generated by this session.
        """
        self._dialect = dialect
        self._bridge: AsyncDatabaseBridge = create_bridge(bridge, is_async=True)  # type: ignore[assignment]

    @property
    def dialect(self) -> str:
        """Active dialect for this session."""
        return self._dialect

    @property
    def bridge(self) -> AsyncDatabaseBridge:
        """Active async database bridge."""
        return self._bridge

    async def execute(
        self, query_or_statement: Query | str, parameters: dict[str, Any] | None = None
    ) -> list[dict[str, Any]]:
        """Asynchronously executes a Query object or raw statement string.

        Args:
            query_or_statement: Voyager Query instance or raw query statement string.
            parameters: Query parameters dictionary (if statement is a string).

        Returns:
            List of result records mapped as dictionaries.
        """
        if hasattr(query_or_statement, "compile"):
            compiled = query_or_statement.compile(dialect=self._dialect)
            return await self._bridge.execute(compiled.statement, compiled.parameters)
        return await self._bridge.execute(str(query_or_statement), parameters)

    async def execute_to_polars(
        self, query_or_statement: Query | str, parameters: dict[str, Any] | None = None
    ) -> pl.DataFrame:
        """Asynchronously executes a query and streams results into a Polars DataFrame.

        Args:
            query_or_statement: Voyager Query instance or raw query statement string.
            parameters: Query parameters dictionary (if statement is a string).

        Returns:
            Columnar Polars DataFrame containing the result records.
        """
        if hasattr(query_or_statement, "compile"):
            compiled = query_or_statement.compile(dialect=self._dialect)
            return await self._bridge.execute_to_polars(compiled.statement, compiled.parameters)
        return await self._bridge.execute_to_polars(str(query_or_statement), parameters)

    async def run_bulk(self, plan: BulkIngestionPlan) -> BulkExecutionResult:
        """Asynchronously executes a BulkIngestionPlan across the database bridge.

        Args:
            plan: Prepared bulk ingestion plan.

        Returns:
            Execution metrics summary including total batches, records, and elapsed time.
        """
        return await self._bridge.execute_bulk(plan)

    def bulk_create(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a bulk node creation plan.

        Args:
            model: Node class to instantiate.
            data: Records or Polars DataFrame to insert.
            batch_size: Maximum records per batch transaction.
            dialect: Override dialect.

        Returns:
            BulkIngestionPlan instance.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_plan(
            model=model,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_upsert(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        key_field: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares an idempotent bulk upsert plan.

        Args:
            model: Node class to upsert.
            data: Records or Polars DataFrame to upsert.
            key_field: Unique key property field name.
            batch_size: Maximum records per batch transaction.
            dialect: Override dialect.

        Returns:
            BulkIngestionPlan instance.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_merge_plan(
            model=model,
            key_field=key_field,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_create_relationships(
        self,
        rel_model: type[Relationship] | str,
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        from_label: str,
        from_key: str,
        to_label: str,
        to_key: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a bulk relationship creation plan.

        Args:
            rel_model: Relationship class or type string.
            data: Records containing from/to keys and edge properties.
            from_label: Source node label.
            from_key: Source node matching property name.
            to_label: Target node label.
            to_key: Target node matching property name.
            batch_size: Maximum edges per batch transaction.
            dialect: Override dialect.

        Returns:
            BulkIngestionPlan instance.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_rel_plan(
            rel_model=rel_model,
            data=data,
            from_label=from_label,
            from_key=from_key,
            to_label=to_label,
            to_key=to_key,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    async def close(self) -> None:
        """Closes the underlying database bridge connection."""
        await self._bridge.close()
