"""Session management and high-level execution facade for Voyager OGM."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from voyager_ogm.ingestion import (
    BulkIngestionPlan,
    create_bulk_create_plan,
    create_bulk_create_rel_plan,
    create_bulk_merge_plan,
)
from voyager_ogm.transaction import Transaction

if TYPE_CHECKING:
    import polars as pl

    from voyager_ogm.models import Node, Relationship


class Session:
    """Graph database session coordinator for Voyager OGM.

    Provides high-throughput bulk ingestion, Unit-of-Work transactions, and query dispatch.
    """

    def __init__(self, dialect: str = "cypher") -> None:
        """Initializes a new Voyager Session.

        Parameters
        ----------
        dialect : str, default="cypher"
            Default query dialect for statements generated by this session ('cypher', 'iso_gql').
        """
        self._dialect = dialect

    @property
    def dialect(self) -> str:
        """Active dialect for this session."""
        return self._dialect

    def transaction(self) -> Transaction:
        """Creates a fresh two-layer rollback transaction context manager.

        Returns
        -------
        Transaction
            Active transaction instance with savepoint support.
        """
        return Transaction()

    def bulk_create(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput bulk node creation execution plan.

        Compiles `UNWIND $batch AS row CREATE (n:Model) SET n.prop = row.prop` and chunks
        the input data/DataFrame into optimal batches.

        Parameters
        ----------
        model : type[Node]
            Node class to instantiate.
        data : list[dict[str, Any]] | pl.DataFrame
            Records or Polars DataFrame to insert.
        batch_size : int, default=50_000
            Maximum records per batch transaction.
        dialect : str, optional
            Override the session default dialect.

        Returns
        -------
        BulkIngestionPlan
            Executable plan containing parameterized batch queries.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_plan(
            model=model,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_upsert(
        self,
        model: type[Node],
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        key_field: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput idempotent bulk upsert (MERGE) execution plan.

        Compiles `UNWIND $batch AS row MERGE (n:Model {key: row.key})` with
        `ON CREATE SET ... ON MATCH SET ...` and chunks the input data/DataFrame.

        Parameters
        ----------
        model : type[Node]
            Node class to upsert.
        data : list[dict[str, Any]] | pl.DataFrame
            Records or Polars DataFrame to upsert.
        key_field : str
            Unique key property field name.
        batch_size : int, default=50_000
            Maximum records per batch transaction.
        dialect : str, optional
            Override the session default dialect.

        Returns
        -------
        BulkIngestionPlan
            Executable plan containing parameterized batch queries.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_merge_plan(
            model=model,
            key_field=key_field,
            data=data,
            batch_size=batch_size,
            dialect=target_dialect,
        )

    def bulk_create_relationships(
        self,
        rel_model: type[Relationship] | str,
        data: list[dict[str, Any]] | pl.DataFrame | Any,
        from_label: str,
        from_key: str,
        to_label: str,
        to_key: str,
        batch_size: int = 50_000,
        dialect: str | None = None,
    ) -> BulkIngestionPlan:
        """Prepares a high-throughput bulk relationship creation execution plan.

        Parameters
        ----------
        rel_model : type[Relationship] | str
            Relationship class or type string.
        data : list[dict[str, Any]] | pl.DataFrame
            Records containing `from_<from_key>`, `to_<to_key>`, and edge properties.
        from_label : str
            Source node label.
        from_key : str
            Source node matching property name.
        to_label : str
            Target node label.
        to_key : str
            Target node matching property name.
        batch_size : int, default=50_000
            Maximum edges per batch transaction.
        dialect : str, optional
            Override the session default dialect.

        Returns
        -------
        BulkIngestionPlan
            Executable plan.
        """
        target_dialect = dialect or self._dialect
        return create_bulk_create_rel_plan(
            rel_model=rel_model,
            data=data,
            from_label=from_label,
            from_key=from_key,
            to_label=to_label,
            to_key=to_key,
            batch_size=batch_size,
            dialect=target_dialect,
        )
